### ISSUE TITLE
Need guidance for .Net 6 InTheHand.BluetoothLE NuGet

### ISSUE THREAD

**Issue by FifthCloud** [inthehand/32feet#235]
I am having the exact problem listed here: [https://github.com/inthehand/32feet/issues/166](https://github.com/inthehand/32feet/issues/166)

InTheHand.BluetoothLE.dll cannot be referenced because it uses built-in support for WinRT, which is no longer supported in .NET 5 and higher.  An updated version of the component supporting .NET 5 is needed. 

Here is my csproj
`<Project Sdk="Microsoft.NET.Sdk">`
`  <PropertyGroup>`
`    <TargetFramework>net6.0</TargetFramework>`
`    <ImplicitUsings>enable</ImplicitUsings>`
`    <Nullable>enable</Nullable>`
`  </PropertyGroup>`
`  <ItemGroup>`
`    <PackageReference Include="InTheHand.BluetoothLE" Version="4.0.25" />`
`  </ItemGroup>`
`</Project>`

If I try to change the TargetFramework with the windows build I still can't get the solution to build. Feels like the answer is obvious, but I am missing it. 

Can someone please guide me as to what I need to do?

The NuGet package I installed is this one: [https://www.nuget.org/packages/InTheHand.BluetoothLE/4.0.25](https://www.nuget.org/packages/InTheHand.BluetoothLE/4.0.25)
Maybe I have chosen the wrong one?

Thanks in advance.

**Comment by peterfoot** [comment]
I've added some details to the original issue #166. If you are using the library in a generic .net 6.0 library and then consuming this from a .net 6 Windows project you'll need to reference InTheHand.BluetoothLE from the consuming project with a .NET 6 Windows tfm e.g. net6.0-windows10.0.19041.0. Currently the library doesn't support Windows 10 SDKs prior to 19041 because this is a good compromise between Bluetooth LE support (available in some form since first Windows 10 release) and various API changes between SDK releases.
