### ISSUE TITLE
Using InTheHand.BluetoothLE.dll in .NET6

### ISSUE THREAD

**Issue by kobelev-dev** [inthehand/32feet#257]
Dear sirs, I created a simple .Net6 project and added your Nu-Get library there. I am getting:

![image](https://user-images.githubusercontent.com/4073539/210731579-d91c1b51-9245-4572-ba16-43388ad00d6c.png)

Is there any way to do something around this?
Should I maybe try to use the WinRT directly?

Thanks,
Kirill

**Comment by peterfoot** [comment]
What is your target platform for the project. Because the implementation is platform specific the NuGet contains net6.0-android, net6.0-ios, net6.0-windows10.0.19041.0 etc. If you try to target an older version of Windows or generic .net6.0 there is no implementation and so it will step down to an earlier .net version dll. While technically Bluetooth LE is supported in older Windows 10 SDKs there are some differences and so that version was selected as a baseline.

**Comment by kobelev-dev** [comment]
Thanks for your prompt response. I found what was wrong. I changed from this

![image](https://user-images.githubusercontent.com/4073539/210858798-5dac0aa5-dd8c-49d7-afcc-03d17d9da26b.png)

 to this:
 
![image](https://user-images.githubusercontent.com/4073539/210858973-cc6dd347-c720-4676-8e42-e29cd0d827dc.png)

After that is started to compile.
By default Visual Studio is not setting the target OS. IMO this piece should be mentioned somewhere in the 32feet docs or Wikis.

**Comment by peterfoot** [comment]
@nref because the library gets its WinRT bindings from having that runtime type set on the assembly it's exposed with the same TFM. The BluetoothLE apis are only available on Windows 10, and the assembly is already marked as compatible down to 10.0.17763.

**Comment by nref** [comment]
I can see now that I am [preaching to the choir](https://inthehand.com/2023/08/21/reinventing-the-wheel-again-bluetooth-on-linux/).  🙂
