### ISSUE TITLE
Filter doesn't work using ScanForDevicesAsync on Windows10

### ISSUE THREAD

**Issue by pinibz** [inthehand/32feet#389]
Hi

I am using the code bellow on windows 10 to scan only for devices that match a known service of a specific device type.
However, it returns **all** the BLE devices around regardless of their service.

 var filter = new BluetoothLEScanFilter();
 filter.Services.Add(my_device_main_service_uuid); 
 var options = new RequestDeviceOptions();
 options.Filters.Add(filter);
  
 foreach (BluetoothDevice sd in await InTheHand.Bluetooth.Bluetooth.ScanForDevicesAsync(options))
 {
     Debug.WriteLine($"Found Device {sd.Id} {sd.Name}  ");
 }

Am I missing something?

Thanks

**Comment by matej-mnoucek** [comment]
Same issue for me. It seems that `BluetoothLEScanFilter` is simply not taken into account.

**Comment by peterfoot** [comment]
Sorry, I thought this was already tracked by an issue. Currently on Windows only the NamePrefix filter is implemented for ScanForDevicesAsync, for the RequestDeviceAsync lookup it is able to build more complex filters and use service uuid. We will have to implement this in the library rather than the discovery filter.

**Comment by peterfoot** [comment]
This is resolved in 4.0.36
